name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Чек-аут кода
        uses: actions/checkout@v4

      - name: Настройка Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'  # или другая версия, которую вы используете

      - name: Установка зависимостей
        run: npm ci

      - name: Сборка проекта
        run: npm run build  # или другая команда, если она отличается

      - name: Загрузка артефакта (опционально)
        uses: actions/upload-artifact@v4
        with:
          name: dist-artifact
          path: dist/
